name: autofix.ci # needs to use this name

on:
  push:
    branches: [main]

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v6.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: 10
          run_install: true

      - name: Format & Lint
        run: |
          pnpm fmt
          pnpm lint

      - uses: autofix-ci/action@v1.3.4
