name: Compress Images (Manual)

on: workflow_dispatch

jobs:
  build:
    name: cadamsdev/image-optimizer-action
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Compress Images
        id: compress-images
        uses: cadamsdev/image-optimizer-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create New Pull Request If Needed
        if: steps.compress-images.outputs.markdown_report != ''
        uses: peter-evans/create-pull-request@v7
        with:
          title: Compressed Images
          branch-suffix: timestamp
          commit-message: "chore: compress images"
          body: ${{ steps.compress-images.outputs.markdown_report }}
