name: WebSub
# example: https://vercel.com/guides/how-can-i-run-end-to-end-tests-after-my-vercel-preview-deployment
permissions:
  contents: read
on:
  deployment_status:

jobs:
  websub:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'production'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v6.0.9
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: true
      - name: Post WebSub
        run: pnpm websub
